In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx

# **Step 1 — Project Title & Overview**

# 🛒 From Raw Data to Business Insights: Retail Sales Data Cleaning & Visualization

## 📌 Project Overview

This project demonstrates a complete data analysis workflow using a real-world retail sales dataset.

The objective is to transform raw transactional data into a clean, reliable dataset and uncover meaningful business insights through data cleaning, feature engineering, and visualization.

### 🎯 Project Objectives

- Load and merge retail sales data
- Assess data quality
- Clean missing, duplicate, and invalid records
- Perform feature engineering
- Explore sales trends using visualizations
- Generate business insights from the cleaned dataset

### 🛠️ Tools & Libraries

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

### 📂 Dataset

**Online Retail Sales II**

# **Step 2 — Import Required Libraries**

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print(" Libraries imported successfully.")

 Libraries imported successfully.

# **Step 3 — Load the Excel File**

In [3]:
file_path = "/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

# **Step 4 — Check the Worksheet Names**

In [4]:
sheet_names = excel_file.sheet_names

print("Available Worksheets:")

for sheet in sheet_names:
    print(f"- {sheet}")

Available Worksheets:
- Year 2009-2010
- Year 2010-2011

# **Load the Data from Both Worksheets**

In [5]:
df_2009 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
df_2010 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

print("2009-2010 Shape :", df_2009.shape)
print("2010-2011 Shape :", df_2010.shape)

2009-2010 Shape : (525461, 8)
2010-2011 Shape : (541910, 8)

# **Step 5 — Add a Year Column**

## 🏷️ Add Year Identifier

Before merging the datasets, we add a **Year** column to each DataFrame.

This preserves the source of every transaction after combining both worksheets.

In [6]:
df_2009["Year"] = "2009-2010"
df_2010["Year"] = "2010-2011"

print("Year column added successfully.")

Year column added successfully.

# **Step 6 — Merge Both DataFrames**

In [7]:
df = pd.concat([df_2009, df_2010], ignore_index=True)

print("Datasets merged successfully.")
print(f"Dataset Shape: {df.shape}")

Datasets merged successfully.
Dataset Shape: (1067371, 9)

# **Step 7 — First Look at the Dataset**

In [8]:
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Rows    : 1,067,371
Columns : 9

# **Step 8 — Display the First 5 Rows**

In [9]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [10]:
print(df.shape[0])
print(df.shape[1])

1067371
9

# **Step 9 — Preview Dataset**

In [11]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [12]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,2009-2010
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,2009-2010
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,2009-2010
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,2009-2010

In [13]:

df.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
851328,565460,23118,PARISIENNE JEWELLERY DRAWER,4,2011-09-05 09:24:00,7.50,16843.0,United Kingdom,2010-2011
851095,565447,22961,JAM MAKING SET PRINTED,12,2011-09-04 15:20:00,1.45,14107.0,United Kingdom,2010-2011
933597,571931,23296,SET OF 6 TEA TIME BAKING CASES,1,2011-10-19 16:59:00,3.29,NaN,United Kingdom,2010-2011
709279,552670,22698,PINK REGENCY TEACUP AND SAUCER,1,2011-05-10 15:06:00,5.79,NaN,United Kingdom,2010-2011
850668,565432,23357,HOT WATER BOTTLE SEX BOMB,1,2011-09-04 13:16:00,4.95,16241.0,United Kingdom,2010-2011

In [14]:
df.sample(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
1036289,579470,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2011-11-29 15:06:00,4.95,16549.0,United Kingdom,2010-2011
182129,506700,84050,PINK HEART SHAPE EGG FRYING PAN,6,2010-05-02 13:46:00,1.65,13136.0,United Kingdom,2009-2010
1049158,580519,22426,ENAMEL WASH BOWL CREAM,1,2011-12-04 14:51:00,8.29,NaN,United Kingdom,2010-2011
706160,552337,22727,ALARM CLOCK BAKELIKE RED,8,2011-05-09 11:34:00,3.75,12621.0,Germany,2010-2011
147341,503426,35921,EASTER BUNNY HANGING GARLAND,2,2010-03-31 17:28:00,5.06,NaN,United Kingdom,2009-2010
24519,491424,48173C,DOOR MAT BLACK FLOCK,2,2009-12-10 19:53:00,6.75,13542.0,United Kingdom,2009-2010
517644,537609,22865,HAND WARMER OWL DESIGN,36,2010-12-07 13:22:00,2.10,17675.0,United Kingdom,2009-2010
390332,526911,20681,PINK POLKADOT CHILDRENS UMBRELLA,6,2010-10-13 15:40:00,3.25,12681.0,France,2009-2010
1003392,577078,23133,LARGE IVORY HEART WALL ORGANISER,1,2011-11-17 15:17:00,16.63,NaN,United Kingdom,2010-2011
712650,552952,22710,WRAP I LOVE LONDON,25,2011-05-12 12:10:00,0.42,13837.0,United Kingdom,2010-2011
600933,542598,21523,DOORMAT FANCY FONT HOME SWEET HOME,1,2011-01-30 10:43:00,7.95,14805.0,United Kingdom,2010-2011
1025113,578681,23491,VINTAGE JINGLE BELLS HEART,2,2011-11-25 08:41:00,8.25,13579.0,United Kingdom,2010-2011
849159,565328,22191,IVORY DINER WALL CLOCK,4,2011-09-02 13:50:00,8.50,14004.0,United Kingdom,2010-2011
851999,565542,22561,WOODEN SCHOOL COLOURING SET,12,2011-09-05 12:06:00,1.65,16820.0,United Kingdom,2010-2011
686202,550470,21915,RED HARMONICA IN BOX,1,2011-04-18 13:49:00,2.46,NaN,United Kingdom,2010-2011
947244,573026,23265,SET OF 3 WOODEN TREE DECORATIONS,12,2011-10-27 13:25:00,1.25,17459.0,United Kingdom,2010-2011
102220,499123,21216,"SET 3 RED SPOT TIN TEA,COFFEE,SUGAR",1,2010-02-24 16:15:00,4.95,14556.0,United Kingdom,2009-2010
674189,549251,85030,FRENCH CHATEAU OVAL PLATTER,2,2011-04-07 12:16:00,1.95,14449.0,United Kingdom,2010-2011
148382,503536,48197,DOOR MAT BIRD ON THE WIRE,1,2010-04-01 13:54:00,7.49,15023.0,United Kingdom,2009-2010
322442,520824,22571,ROCKING HORSE RED CHRISTMAS,6,2010-08-31 12:30:00,1.66,NaN,United Kingdom,2009-2010

In [15]:
df.sample(5, random_state=42)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom,2009-2010
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom,2010-2011
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom,2009-2010
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom,2009-2010
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom,2009-2010