In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx

# **Step 1 — Project Title & Overview**

# 🛒 From Raw Data to Business Insights: Retail Sales Data Cleaning & Visualization

## 📌 Project Overview

This project demonstrates a complete data analysis workflow using a real-world retail sales dataset.

The objective is to transform raw transactional data into a clean, reliable dataset and uncover meaningful business insights through data cleaning, feature engineering, and visualization.

### 🎯 Project Objectives

- Load and merge retail sales data
- Assess data quality
- Clean missing, duplicate, and invalid records
- Perform feature engineering
- Explore sales trends using visualizations
- Generate business insights from the cleaned dataset

### 🛠️ Tools & Libraries

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

### 📂 Dataset

**Online Retail Sales II**

# **Step 2 — Import Required Libraries**

In [19]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print(" Libraries imported successfully.")

 Libraries imported successfully.

# **Step 3 — Load the Excel File**

In [20]:
file_path = "/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

# **Step 4 — Check the Worksheet Names**

In [21]:
sheet_names = excel_file.sheet_names

print("Available Worksheets:")

for sheet in sheet_names:
    print(f"- {sheet}")

Available Worksheets:
- Year 2009-2010
- Year 2010-2011

# **Load the Data from Both Worksheets**

In [22]:
df_2009 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
df_2010 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

print("2009-2010 Shape :", df_2009.shape)
print("2010-2011 Shape :", df_2010.shape)

2009-2010 Shape : (525461, 8)
2010-2011 Shape : (541910, 8)

# **Step 5 — Add a Year Column**

## 🏷️ Add Year Identifier

Before merging the datasets, we add a **Year** column to each DataFrame.

This preserves the source of every transaction after combining both worksheets.

In [23]:
df_2009["Year"] = "2009-2010"
df_2010["Year"] = "2010-2011"

print("Year column added successfully.")

Year column added successfully.

# **Step 6 — Merge Both DataFrames**

In [24]:
df = pd.concat([df_2009, df_2010], ignore_index=True)

print("Datasets merged successfully.")
print(f"Dataset Shape: {df.shape}")

Datasets merged successfully.
Dataset Shape: (1067371, 9)

# **Step 7 — First Look at the Dataset**

In [25]:
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Rows    : 1,067,371
Columns : 9

# **Step 8 — Display the First 5 Rows**

In [26]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [27]:
print(df.shape[0])
print(df.shape[1])

1067371
9

# **Step 9 — Preview Dataset**

In [28]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [29]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,2009-2010
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,2009-2010
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,2009-2010
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,2009-2010

In [30]:

df.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
728460,554511,22668,PINK BABY BUNTING,1,2011-05-24 15:52:00,5.79,NaN,United Kingdom,2010-2011
701808,551997,21790,VINTAGE SNAP CARDS,1,2011-05-05 15:47:00,1.63,NaN,United Kingdom,2010-2011
211286,509858,20829,GLITTER HANGING BUTTERFLY STRING,8,2010-05-26 09:52:00,2.10,13911.0,United Kingdom,2009-2010
205356,509195,15056P,EDWARDIAN PARASOL PINK,3,2010-05-20 18:18:00,5.95,12712.0,Germany,2009-2010
487833,535078,22197,SMALL POPCORN HOLDER,200,2010-11-25 08:20:00,0.72,16401.0,United Kingdom,2009-2010

In [31]:
df.sample(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
395415,527366,22586,FELTCRAFT HAIRBAND PINK AND BLUE,2,2010-10-17 11:24:00,0.85,15571.0,United Kingdom,2009-2010
555442,538839,71459,HANGING JAM JAR T-LIGHT HOLDER,12,2010-12-14 13:10:00,0.85,14606.0,United Kingdom,2010-2011
303303,518950,21213,PACK OF 72 SKULL CAKE CASES,24,2010-08-12 15:06:00,0.55,15296.0,United Kingdom,2009-2010
608675,543292,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,48,2011-02-07 11:15:00,1.25,14534.0,United Kingdom,2010-2011
702581,552042,22072,RED RETROSPOT TEA CUP AND SAUCER,8,2011-05-06 09:00:00,3.75,13952.0,United Kingdom,2010-2011
74072,496081,21812,GARLAND WITH HEARTS AND BELLS,1,2010-01-28 17:54:00,4.95,17905.0,United Kingdom,2009-2010
1058823,581023,22507,MEMO BOARD RETROSPOT DESIGN,4,2011-12-07 10:35:00,10.79,NaN,United Kingdom,2010-2011
723772,554030,22698,PINK REGENCY TEACUP AND SAUCER,6,2011-05-20 13:56:00,2.95,16497.0,United Kingdom,2010-2011
388257,526738,22456,NATURAL SLATE CHALKBOARD LARGE,1,2010-10-12 18:02:00,10.17,NaN,United Kingdom,2009-2010
73071,495993,22100,SKULLS SQUARE TISSUE BOX,1,2010-01-28 11:33:00,1.25,14672.0,United Kingdom,2009-2010
1066969,581498,23564,EGG CUP MILKMAID INGRID,1,2011-12-09 10:26:00,2.46,NaN,United Kingdom,2010-2011
476919,534209,22777,GLASS CLOCHE LARGE,2,2010-11-21 15:55:00,8.50,14146.0,United Kingdom,2009-2010
456408,532669,21591,COSY HOUR CIGAR BOX MATCHES,6,2010-11-14 11:46:00,1.25,NaN,United Kingdom,2009-2010
1047316,580367,23173,REGENCY TEAPOT ROSES,1,2011-12-02 16:39:00,19.96,NaN,United Kingdom,2010-2011
497218,535835,22560,TRADITIONAL MODELLING CLAY,1,2010-11-29 09:46:00,2.51,NaN,United Kingdom,2009-2010
770435,558564,23199,JUMBO BAG APPLES,2,2011-06-30 13:45:00,2.08,14057.0,United Kingdom,2010-2011
113717,500275,20734,SILVER MINI TAPE MEASURE,1,2010-03-05 14:45:00,1.66,NaN,United Kingdom,2009-2010
651687,547069,22989,SET 2 PANTRY DESIGN TEA TOWELS,2,2011-03-20 13:52:00,3.25,16710.0,United Kingdom,2010-2011
72902,495953,21640,ASSORTED TUTTI FRUTTI FOB NOTEBOOK,1,2010-01-27 17:56:00,1.66,NaN,United Kingdom,2009-2010
878356,567700,22138,BAKING SET 9 PIECE RETROSPOT,6,2011-09-22 09:33:00,4.95,16379.0,United Kingdom,2010-2011

In [32]:
df.sample(5, random_state=42)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom,2009-2010
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom,2010-2011
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom,2009-2010
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom,2009-2010
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom,2009-2010

# **Step 10 — Check the Dataset Structure**

In [33]:
print("=" * 60)
print("Dataset Information")
print("=" * 60)

df.info()

============================================================
Dataset Information
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
 8   Year         1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 73.3+ MB

# **Step 11 — Statistical Summary**

In [34]:
df.describe(include="all").T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Invoice,1067371.0,53628.0,537434.0,1350.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockCode,1067371,5305,85123A,5829,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Description,1062989,5698,WHITE HANGING HEART T-LIGHT HOLDER,5918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,1067371.0,NaN,NaN,NaN,9.938898,-80995.0,1.0,3.0,10.0,80995.0,172.705794
InvoiceDate,1067371,NaN,NaN,NaN,2011-01-02 21:13:55.394028544,2009-12-01 07:45:00,2010-07-09 09:46:00,2010-12-07 15:28:00,2011-07-22 10:23:00,2011-12-09 12:50:00,NaN
Price,1067371.0,NaN,NaN,NaN,4.649388,-53594.36,1.25,2.1,4.15,38970.0,123.553059
Customer ID,824364.0,NaN,NaN,NaN,15324.638504,12346.0,13975.0,15255.0,16797.0,18287.0,1697.46445
Country,1067371,43,United Kingdom,981330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,1067371,2,2010-2011,541910,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Step 12 — Data Quality Assessment**

In [35]:
# Missing Values
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum() / len(df) * 100).round(2)
}).sort_values("Missing Values", ascending=False)

print("Missing Values")
display(missing)

print(f"\nDuplicate Rows      : {df.duplicated().sum():,}")
print(f"Negative Quantity   : {(df['Quantity'] < 0).sum():,}")
print(f"Zero Quantity       : {(df['Quantity'] == 0).sum():,}")
print(f"Negative Price      : {(df['Price'] < 0).sum():,}")
print(f"Zero Price          : {(df['Price'] == 0).sum():,}")
print(f"Cancelled Orders    : {df['Invoice'].astype(str).str.startswith('C').sum():,}")

Missing Values

             Missing Values  Percentage
Customer ID          243007       22.77
Description            4382        0.41
Invoice                   0        0.00
Quantity                  0        0.00
StockCode                 0        0.00
InvoiceDate               0        0.00
Price                     0        0.00
Country                   0        0.00
Year                      0        0.00

Duplicate Rows      : 12,133
Negative Quantity   : 22,950
Zero Quantity       : 0
Negative Price      : 5
Zero Price          : 6,202
Cancelled Orders    : 19,494