In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx

# **Step 1 — Project Title & Overview**

# 🛒 From Raw Data to Business Insights: Retail Sales Data Cleaning & Visualization

## 📌 Project Overview

This project demonstrates a complete data analysis workflow using a real-world retail sales dataset.

The objective is to transform raw transactional data into a clean, reliable dataset and uncover meaningful business insights through data cleaning, feature engineering, and visualization.

### 🎯 Project Objectives

- Load and merge retail sales data
- Assess data quality
- Clean missing, duplicate, and invalid records
- Perform feature engineering
- Explore sales trends using visualizations
- Generate business insights from the cleaned dataset

### 🛠️ Tools & Libraries

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

### 📂 Dataset

**Online Retail Sales II**

# **Step 2 — Import Required Libraries**

In [3]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print(" Libraries imported successfully.")

 Libraries imported successfully.

# **Step 3 — Load the Excel File**

In [4]:
file_path = "/kaggle/input/datasets/muhammadumer7804/online-retail-sales-ii/online_retail_II.xlsx"

excel_file = pd.ExcelFile(file_path)

print("Dataset loaded successfully!")

Dataset loaded successfully!

# **Step 4 — Check the Worksheet Names**

In [5]:
sheet_names = excel_file.sheet_names

print("Available Worksheets:")

for sheet in sheet_names:
    print(f"- {sheet}")

Available Worksheets:
- Year 2009-2010
- Year 2010-2011

# **Load the Data from Both Worksheets**

In [6]:
df_2009 = pd.read_excel(file_path, sheet_name="Year 2009-2010")
df_2010 = pd.read_excel(file_path, sheet_name="Year 2010-2011")

print("2009-2010 Shape :", df_2009.shape)
print("2010-2011 Shape :", df_2010.shape)

2009-2010 Shape : (525461, 8)
2010-2011 Shape : (541910, 8)

# **Step 5 — Add a Year Column**

## 🏷️ Add Year Identifier

Before merging the datasets, we add a **Year** column to each DataFrame.

This preserves the source of every transaction after combining both worksheets.

In [7]:
df_2009["Year"] = "2009-2010"
df_2010["Year"] = "2010-2011"

print("Year column added successfully.")

Year column added successfully.

# **Step 6 — Merge Both DataFrames**

In [8]:
df = pd.concat([df_2009, df_2010], ignore_index=True)

print("Datasets merged successfully.")
print(f"Dataset Shape: {df.shape}")

Datasets merged successfully.
Dataset Shape: (1067371, 9)

# **Step 7 — First Look at the Dataset**

In [9]:
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

Rows    : 1,067,371
Columns : 9

# **Step 8 — Display the First 5 Rows**

In [10]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [11]:
print(df.shape[0])
print(df.shape[1])

1067371
9

# **Step 9 — Preview Dataset**

In [12]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010

In [13]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009-2010
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009-2010
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009-2010
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom,2009-2010
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009-2010
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom,2009-2010
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom,2009-2010
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom,2009-2010

In [14]:

df.sample(5)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
656585,547547,85099C,JUMBO BAG BAROQUE BLACK WHITE,1,2011-03-23 15:30:00,4.13,NaN,United Kingdom,2010-2011
682038,550149,21244,BLUE POLKADOT PLATE,5,2011-04-14 14:37:00,1.69,13069.0,United Kingdom,2010-2011
718625,C553516,21658,GLASS BEURRE DISH,-1,2011-05-17 14:07:00,3.95,14911.0,EIRE,2010-2011
245838,513190,21115,ROSE CARAVAN DOORSTOP,1,2010-06-22 14:21:00,6.75,16894.0,United Kingdom,2009-2010
674179,549250,22329,ROUND CONTAINER SET OF 5 RETROSPOT,1,2011-04-07 12:10:00,1.65,14446.0,United Kingdom,2010-2011

In [15]:
df.sample(20)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
227036,511307,21201,TROPICAL HONEYCOMB PAPER GARLAND,4,2010-06-07 16:01:00,2.55,13983.0,United Kingdom,2009-2010
700777,551952,21936,RED RETROSPOT PICNIC BAG,50,2011-05-05 11:47:00,2.55,15838.0,United Kingdom,2010-2011
948244,573117,23542,WALL ART 70'S ALPHABET,4,2011-10-27 16:11:00,8.25,16688.0,United Kingdom,2010-2011
940265,C572488,22972,CHILDREN'S SPACEBOY MUG,-1,2011-10-24 13:57:00,1.65,12474.0,Germany,2010-2011
419619,529514,85031B,BLOSSOM IMAGES SCRAP BOOK SET,24,2010-10-28 15:05:00,1.25,13669.0,United Kingdom,2009-2010
966274,574547,85054,FRENCH ENAMEL POT W LID,1,2011-11-04 15:08:00,2.95,17841.0,United Kingdom,2010-2011
635835,545685,21314,SMALL GLASS HEART TRINKET POT,4,2011-03-06 11:55:00,2.10,14499.0,United Kingdom,2010-2011
724751,554094,22082,RIBBON REEL STRIPES DESIGN,5,2011-05-22 12:49:00,1.65,15716.0,United Kingdom,2010-2011
899382,569367,22182,CAKE STAND VICTORIAN FILIGREE SMALL,1,2011-10-03 15:28:00,4.95,13994.0,United Kingdom,2010-2011
359670,C524235,21096,SET/6 FRUIT SALAD PAPER PLATES,-7008,2010-09-28 11:02:00,0.13,14277.0,France,2009-2010
483000,534669,20983,12 PENCILS TALL TUBE RED RETROSPOT,5,2010-11-23 13:59:00,0.85,12577.0,France,2009-2010
273043,515911,22629,SPACEBOY LUNCH BOX,12,2010-07-15 13:19:00,1.65,14298.0,United Kingdom,2009-2010
600020,542434,22131,FOOD CONTAINER SET 3 LOVE HEART,12,2011-01-28 10:47:00,1.95,16755.0,United Kingdom,2010-2011
738527,555518,22149,FELTCRAFT 6 FLOWER FRIENDS,6,2011-06-05 10:58:00,2.10,14891.0,United Kingdom,2010-2011
1018086,578140,23388,WOODLAND MINI BACKPACK,50,2011-11-23 10:58:00,3.75,14646.0,Netherlands,2010-2011
848707,C565284,21232,STRAWBERRY CERAMIC TRINKET BOX,-1,2011-09-02 11:31:00,1.25,12471.0,Germany,2010-2011
189179,507373,21533,RETRO SPOT LARGE MILK JUG,1,2010-05-09 10:47:00,4.95,13595.0,United Kingdom,2009-2010
31093,491969,20716,PARTY FOOD SHOPPER BAG,1,2009-12-14 17:57:00,2.57,NaN,United Kingdom,2009-2010
617548,544177,22294,HEART FILIGREE DOVE SMALL,24,2011-02-16 14:27:00,1.25,13001.0,United Kingdom,2010-2011
577921,540797,22168,ORGANISER WOOD ANTIQUE WHITE,1,2011-01-11 12:05:00,8.50,15107.0,United Kingdom,2010-2011

In [16]:
df.sample(5, random_state=42)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year
455941,532657,21314,SMALL GLASS HEART TRINKET POT,12,2010-11-14 11:10:00,2.10,14562.0,United Kingdom,2009-2010
826291,563214,22383,LUNCH BAG SUKI DESIGN,2,2011-08-14 12:56:00,1.65,16370.0,United Kingdom,2010-2011
191636,507597,22561,WOODEN SCHOOL COLOURING SET,12,2010-05-10 13:21:00,1.65,17700.0,United Kingdom,2009-2010
25864,491634,21588,RETRO SPOT GIANT TUBE MATCHES,1,2009-12-11 15:40:00,2.55,17841.0,United Kingdom,2009-2010
73233,496007,85232B,SET/3 RUSSIAN DOLL STACKING TINS,3,2010-01-28 12:32:00,4.95,15203.0,United Kingdom,2009-2010

# **10 — Check the Dataset Structure**

In [17]:
print("=" * 60)
print("Dataset Information")
print("=" * 60)

df.info()

============================================================
Dataset Information
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
 8   Year         1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 73.3+ MB